import {useEffect,useState} from "react";
type Role="Administrador"|"Dirección"|"Líder"|"Colaborador";
type Task={id:number,title:string,owner:string,area:string,progress:number,target:string,evidence:boolean,status:string};
const initial:Task[]=[
 {id:1,title:"Contactar 50 prospectos diariamente",owner:"Dante",area:"Ventas",progress:82,target:"50 contactos/día",evidence:true,status:"En tiempo"},
 {id:2,title:"Concretar 10 visitas con clientes por semana",owner:"Dante",area:"Ventas",progress:70,target:"10 visitas/semana",evidence:true,status:"En riesgo"},
 {id:3,title:"Generar campaña de captación B2B",owner:"Verónica",area:"Marketing",progress:52,target:"400 leads/mes",evidence:false,status:"En riesgo"},
 {id:4,title:"Reducir tiempo de elaboración de propuestas",owner:"Jorge",area:"Operaciones",progress:35,target:"Propuesta < 48 h",evidence:false,status:"Bloqueado"}];
const users:Record<Role,string>={"Administrador":"Jorge Mejía","Dirección":"Gabriel Sabogal","Líder":"Daniela Juárez","Colaborador":"Dante"};
const menus:Record<Role,string[]>={"Administrador":["Resumen","Estructura organizacional","Usuarios y roles","Periodos","Configuración EDD"],"Dirección":["Resumen","Objetivos estratégicos","Mapa de cascada","Gantt corporativo","Alertas"],"Líder":["Mis objetivos","Plan del equipo","Delegar actividades","Dependencias","Avances"],"Colaborador":["Mi tablero","Mis metas","Mis actividades","Evidencias","Historial"]};
const areas=[{name:"Ventas",weight:55,progress:76,expected:74,color:"#1774d1",owner:"Daniela Juárez"},{name:"Marketing",weight:25,progress:52,expected:68,color:"#8a5bd2",owner:"Nydia Borja"},{name:"Operaciones",weight:20,progress:35,expected:60,color:"#e19818",owner:"Gabriel Sabogal"}];
export default function Home(){
 const [role,setRole]=useState<Role>("Administrador"),[page,setPage]=useState("Resumen"),[tasks,setTasks]=useState(initial),[modal,setModal]=useState(""),[toast,setToast]=useState(""),[smart,setSmart]=useState(false),[selected,setSelected]=useState(1);
 useEffect(()=>{const s=localStorage.getItem("cascade-tasks");if(s)try{setTasks(JSON.parse(s))}catch{}},[]);
 useEffect(()=>localStorage.setItem("cascade-tasks",JSON.stringify(tasks)),[tasks]);
 const corporate=Math.round(areas.reduce((a,x)=>a+x.progress*x.weight/100,0));
 const change=(r:Role)=>{setRole(r);setPage(menus[r][0]);setModal("")};
 const update=(id:number,p:number)=>{setTasks(t=>t.map(x=>x.id===id?{...x,progress:p,status:p>=80?"En tiempo":p>=50?"En riesgo":"Bloqueado"}:x));setToast("Avance actualizado: la cascada fue recalculada");setTimeout(()=>setToast(""),2300)};
 const title=role==="Administrador"?"Centro de administración":role==="Dirección"?"Estrategia corporativa":role==="Líder"?"Plan de mi equipo":"Mi contribución";
 return <main className="app"><aside><div className="brand"><b>IC</b><p>INTER-CON<span>OBJETIVOS EN CASCADA</span></p></div><label className="demo">VISTA DE DEMOSTRACIÓN<select value={role} onChange={e=>change(e.target.value as Role)}>{Object.keys(users).map(r=><option key={r}>{r}</option>)}</select><small>{users[role]}</small></label><nav>{menus[role].map((m,i)=><button key={m} className={page===m?"active":""} onClick={()=>setPage(m)}><i>{["▦","◎","⌘","☷","⚙"][i]}</i>{m}</button>)}</nav><div className="roleCard"><span>ROL ACTIVO</span><b>{role}</b><small>{role==="Administrador"?"Control total del sistema":role==="Dirección"?"Define y asigna objetivos":role==="Líder"?"Desglosa y delega metas":"Ejecuta y demuestra avances"}</small></div></aside>
 <section className="content"><header><div><small>FY 2026 · OCT 2025 — SEP 2026</small><h1>{title}</h1><p>{page}</p></div><div><button className="ghost">⇩ Reporte</button>{role==="Dirección"&&<button className="primary" onClick={()=>setModal("objective")}>＋ Nuevo objetivo</button>}{role==="Líder"&&<button className="primary" onClick={()=>setModal("delegate")}>＋ Delegar actividad</button>}{role==="Colaborador"&&<button className="primary" onClick={()=>setModal("evidence")}>＋ Registrar avance</button>}{role==="Administrador"&&<button className="primary" onClick={()=>setToast("Configuración guardada")}>Guardar configuración</button>}</div></header>
 {role==="Administrador"&&<Admin page={page}/>}
 {role==="Dirección"&&<Direction page={page} corporate={corporate}/>}
 {role==="Líder"&&<Leader page={page} tasks={tasks} open={()=>setModal("delegate")}/>}
 {role==="Colaborador"&&<Collaborator page={page} tasks={tasks} update={update} evidence={id=>{setSelected(id);setModal("evidence")}}/>}</section>
 {toast&&<div className="toast">✓ {toast}</div>}
 {modal==="objective"&&<Objective close={()=>setModal("")} smart={smart} setSmart={setSmart}/>}
 {modal==="delegate"&&<Delegate close={()=>setModal("")} add={t=>{setTasks(x=>[...x,{id:Date.now(),title:t,owner:"Dante",area:"Ventas",progress:0,target:"10 por semana",evidence:false,status:"Pendiente"}]);setModal("");setToast("Actividad delegada a Dante")}}/>}
 {modal==="evidence"&&<Evidence task={tasks.find(x=>x.id===selected)||tasks[0]} close={()=>setModal("")} save={p=>{update(selected,p);setTasks(x=>x.map(t=>t.id===selected?{...t,evidence:true}:t));setModal("")}}/>}</main>}
function Admin({page}:{page:string}){return <><Hero type="admin" label="GOBIERNO DEL SISTEMA" title="La estructura que alimentará la EDD 2027" desc="Administra usuarios, jerarquías, periodos, permisos, escalas y reglas de integración." stat="94" statLabel="USUARIOS ACTIVOS"/><section className="kpis"><K n="4" l="Roles configurados" s="Admin · Dirección · Líder · Colaborador"/><K n="6" l="Áreas registradas" s="Estructura sincronizada"/><K n="87%" l="Perfiles completos" s="12 requieren revisión"/><K n="FY26" l="Periodo activo" s="Cierra 30 sep 2026"/></section><section className="grid2"><article className="card"><Title a="Matriz de permisos" b="Acciones autorizadas por rol"/><table><thead><tr><th>FUNCIÓN</th><th>ADMIN</th><th>DIRECCIÓN</th><th>LÍDER</th><th>COLAB.</th></tr></thead><tbody>{[["Configurar sistema","✓","—","—","—"],["Crear objetivos estratégicos","✓","✓","—","—"],["Delegar metas y actividades","✓","—","✓","—"],["Actualizar avance y evidencia","✓","—","✓","✓"],["Modificar avance de terceros","✓","—","—","—"]].map(r=><tr key={r[0]}>{r.map((x,i)=><td key={i} className={x==="✓"?"yes":""}>{x}</td>)}</tr>)}</tbody></table></article><article className="card settings"><Title a={page} b="Parámetros del módulo"/>{["Validación SMART obligatoria","Evidencia obligatoria al cierre","Permitir equipos interárea","Integrar resultados con EDD","Permitir cambiar ponderaciones"].map((x,i)=><Toggle key={x} n={x} on={i<4}/>)}</article></section><section className="card eddMap"><div><b>Objetivos FY26</b><i>→</i><b>Metas individuales</b><i>→</i><b>Resultado validado</b><i>→</i><strong>EDD 2027</strong></div><p>La calificación se precargará con el cumplimiento ponderado; cualquier ajuste del líder requerirá justificación.</p></section></>}
function Direction({page,corporate}:{page:string,corporate:number}){return <><Hero label="OBJETIVO ESTRATÉGICO · OBJ-2026-01" title="Aumentar 30% las ventas vs. FY 2025" desc="Base FY25: 100 ventas · Meta FY26: 130 ventas · Responsable ejecutivo: Gabriel Sabogal" stat={corporate+"%"} statLabel="AVANCE CONSOLIDADO" chips/><section className="kpis"><K n="118" l="Ventas proyectadas" s="Meta: 130"/><K n="+18%" l="Crecimiento actual" s="Faltan 12 puntos"/><K n="3" l="Áreas responsables" s="Una requiere intervención"/><K n="15 sep" l="Próximo hito" s="Revisión ejecutiva"/></section><section className="cascadeGrid"><article className="card cascade"><Title a={page==="Gantt corporativo"?"Calendario corporativo":"Embudo de contribución"} b="El avance sube desde las actividades hasta el objetivo"/><div className="rootNode"><span>OBJETIVO CORPORATIVO</span><b>Aumentar ventas +30%</b><strong>{corporate}%</strong></div><div className="connector"/><div className="areaNodes">{areas.map(a=><div className={a.progress<a.expected-10?"node stuck":"node"} key={a.name}><span>{a.name} · {a.weight}% del objetivo</span><b>{a.progress}%</b><div><i style={{width:a.progress+"%",background:a.color}}/></div><small>{a.owner}</small>{a.progress<a.expected-10&&<em>⚠ CUELLO DE BOTELLA</em>}</div>)}</div><div className="tip">✦ <p><b>Diagnóstico:</b> Marketing y Operaciones explican el rezago. Ventas está 2 puntos arriba del plan; no requiere intervención general.</p></div></article><article className="card"><Title a="Decisiones recomendadas" b="Prioridad calculada por impacto"/><Decision n="1" color="red" area="Operaciones" text="La entrega de propuestas tarda más de 48 h y frena cierres comerciales."/><Decision n="2" color="amber" area="Marketing" text="Faltan 148 leads para cumplir el ritmo mensual esperado."/><Decision n="3" color="green" area="Ventas" text="El equipo cumple el volumen de prospección y visitas."/></article></section></>}
function Leader({page,tasks,open}:{page:string,tasks:Task[],open:()=>void}){return <><Hero label="APORTACIÓN ASIGNADA · VENTAS" title="Generar 72 de las 130 ventas del FY 2026" desc="Tu área representa el 55% del objetivo corporativo. Divide la meta entre responsables y coordina dependencias." stat="76%" statLabel="AVANCE DEL ÁREA"/><section className="kpis"><K n="4" l="Colaboradores asignados" s="Dante · Mayra · Ana · Daniela"/><K n="55%" l="Peso en el objetivo" s="72 ventas comprometidas"/><K n="2" l="Dependencias externas" s="Marketing · Operaciones"/><K n="1" l="Meta en riesgo" s="Requiere seguimiento"/></section><section className="grid2"><article className="card"><Title a={page} b="Distribución de metas individuales"/>{[["Dante","24 ventas",70],["Mayra","18 ventas",82],["Ana","18 ventas",76],["Daniela","12 ventas",88]].map(([n,m,p])=><div className="person" key={n as string}><b>{(n as string).slice(0,2).toUpperCase()}</b><p><strong>{n}</strong><span>{m}</span></p><div><i style={{width:p+"%"}}/></div><em>{p}%</em><button>Ver plan</button></div>)}<button className="full primary" onClick={open}>＋ Delegar nueva actividad</button></article><article className="card"><Title a="Dependencias interárea" b="Solicitudes que condicionan tu resultado"/><Dep area="Marketing" task="Entregar 400 leads calificados al mes" p={52}/><Dep area="Operaciones" task="Emitir propuestas en menos de 48 h" p={35}/><div className="tip">✦ <p><b>La meta de Dante está en riesgo</b><span>Las visitas se están logrando, pero 3 propuestas llevan más de 48 horas pendientes.</span></p></div></article></section></>}
function Collaborator({page,tasks,update,evidence}:{page:string,tasks:Task[],update:(i:number,p:number)=>void,evidence:(i:number)=>void}){const mine=tasks.filter(x=>x.owner==="Dante");return <><Hero label="MI META · CONTRIBUCIÓN A VENTAS" title="Concretar 24 ventas durante FY 2026" desc="Esta meta aporta 33% al objetivo del área y 18% al objetivo corporativo." stat="70%" statLabel="MI CUMPLIMIENTO"/><section className="kpis"><K n="17/24" l="Ventas logradas" s="Faltan 7"/><K n="8/10" l="Visitas esta semana" s="Quedan 2"/><K n="43/50" l="Contactos hoy" s="Quedan 7"/><K n="2" l="Evidencias pendientes" s="Antes del viernes"/></section><section className="collabGrid"><article className="card"><Title a={page} b="Actualiza tu actividad; el resultado sube automáticamente"/>{mine.map(t=><div className="task" key={t.id}><div className="check">{t.progress>=100?"✓":t.id}</div><div className="taskMain"><b>{t.title}</b><span>Meta: {t.target}</span><div><i style={{width:t.progress+"%"}}/></div></div><strong>{t.progress}%</strong><input aria-label={"Avance "+t.title} type="range" value={t.progress} onChange={e=>update(t.id,+e.target.value)}/><button onClick={()=>evidence(t.id)}>{t.evidence?"Ver evidencia":"Adjuntar"}</button></div>)}</article><article className="card impact"><Title a="Así se mueve la cascada" b="Tu trabajo impacta los niveles superiores"/>{[["Contactos diarios","82%"],["Visitas semanales","70%"],["Mi meta de ventas","70%"],["Objetivo de Ventas","76%"]].map((x,i)=><div key={x[0]}><div className="step"><b>{i+1}</b><p>{x[0]}<strong>{x[1]}</strong></p></div>{i<3&&<i className="up">↑</i>}</div>)}<div className="tip">✦ <p><b>Qué necesitas hacer ahora</b><span>Agenda 2 visitas adicionales antes del viernes para recuperar el ritmo.</span></p></div></article></section></>}
function Hero({label,title,desc,stat,statLabel,chips}:{type?:string,label:string,title:string,desc:string,stat:string,statLabel:string,chips?:boolean}){return <section className="hero"><div><span>{label}</span><h2>{title}</h2><p>{desc}</p>{chips&&<div className="chips">{["Específico ✓","Medible ✓","Alcanzable ✓","Relevante ✓","Temporal ✓"].map(x=><b key={x}>{x}</b>)}</div>}</div><div className="ring"><b>{stat}</b><span>{statLabel}</span></div></section>}
function Objective({close,smart,setSmart}:{close:()=>void,smart:boolean,setSmart:(v:boolean)=>void}){return <Modal close={close}><span className="ai">✦ ASISTENTE SMART</span><h2>Crear objetivo estratégico</h2><p>Define el resultado; la IA verificará calidad, coherencia y medición.</p><label>Objetivo<input defaultValue="Aumentar 30% las ventas respecto al año fiscal anterior"/></label><div className="fields"><label>Valor base<input defaultValue="100 ventas"/></label><label>Meta<input defaultValue="130 ventas"/></label></div><div className="fields"><label>Periodo<select><option>FY 2026</option></select></label><label>Fecha límite<input type="date" defaultValue="2026-09-30"/></label></div><label>Áreas responsables<select multiple defaultValue={["Ventas","Marketing","Operaciones"]}><option>Ventas</option><option>Marketing</option><option>Operaciones</option></select></label>{smart&&<div className="smart"><b>94</b><p><strong>Objetivo SMART aprobado</strong><span>✓ Específico · ✓ Medible · ✓ Alcanzable · ✓ Relevante · ✓ Temporal</span><small>Sugerencia: documentar la fuente oficial del valor base.</small></p></div>}<Actions close={close} go={()=>smart?close():setSmart(true)} text={smart?"Crear y asignar":"Validar con IA"}/></Modal>}
function Delegate({close,add}:{close:()=>void,add:(s:string)=>void}){const [t,setT]=useState("Concretar 10 visitas con clientes por semana");return <Modal close={close}><span className="ai">DELEGACIÓN DE ACTIVIDAD</span><h2>Asignar contribución</h2><p>Puede asignarse a tu equipo o solicitar apoyo de otra área.</p><label>Actividad<input value={t} onChange={e=>setT(e.target.value)}/></label><div className="fields"><label>Responsable<select><option>Dante · Ventas</option><option>Mayra · Ventas</option><option>Jorge · Inteligencia de Negocios</option><option>Verónica · Marketing</option></select></label><label>Meta<input defaultValue="10 por semana"/></label></div><label>Vinculada con<select><option>Generar 72 ventas del FY 2026</option></select></label><Actions close={close} go={()=>add(t)} text="Asignar actividad"/></Modal>}
function Evidence({task,close,save}:{task:Task,close:()=>void,save:(p:number)=>void}){const [p,setP]=useState(task.progress);return <Modal close={close}><span className="ai">REGISTRO DE AVANCE</span><h2>{task.title}</h2><p>El avance actualizará tu meta, el resultado del área y el objetivo estratégico.</p><label>Avance reportado: {p}%<input type="range" value={p} onChange={e=>setP(+e.target.value)}/></label><label>Comentario<textarea defaultValue="Se realizaron las actividades programadas y se adjunta evidencia del resultado."/></label><label className="upload">＋ Adjuntar evidencia<input type="file"/></label><Actions close={close} go={()=>save(p)} text="Guardar y recalcular"/></Modal>}
function Modal({children,close}:{children:React.ReactNode,close:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="x" onClick={close}>×</button>{children}</div></div>}
function Actions({close,go,text}:{close:()=>void,go:()=>void,text:string}){return <div className="actions"><button className="ghost" onClick={close}>Cancelar</button><button className="primary" onClick={go}>✦ {text}</button></div>}
function K({n,l,s}:{n:string,l:string,s:string}){return <article><b>{n}</b><p>{l}<span>{s}</span></p></article>}
function Title({a,b}:{a:string,b:string}){return <div className="cardTitle"><div><h3>{a}</h3><p>{b}</p></div><button>•••</button></div>}
function Toggle({n,on}:{n:string,on:boolean}){return <label className="toggle"><span>{n}</span><input type="checkbox" defaultChecked={on}/><i/></label>}
function Decision({n,color,area,text}:{n:string,color:string,area:string,text:string}){return <div className={"decision "+color}><b>{n}</b><p><strong>{area}</strong><span>{text}</span><button>Revisar detalle →</button></p></div>}
function Dep({area,task,p}:{area:string,task:string,p:number}){return <div className="dependency"><b>{area.slice(0,2).toUpperCase()}</b><p><strong>{area}</strong><span>{task}</span><small>Responsable externo · Avance {p}%</small></p><em className={p<50?"bad":""}>{p<50?"Bloqueo":"En riesgo"}</em></div>}
