import {FormEvent,useEffect,useMemo,useState} from "react";

type Role="Administrador"|"Dirección"|"Líder"|"Colaborador";
type User={id:string;name:string;email:string;password:string;role:Role;area:string;leader:string};
type Project={id:string;name:string;objective:string;areas:string[];base:number;target:number;unit:string;start:string;end:string;progress:number;owner:string;priority:"Alta"|"Media"|"Baja"};
type Task={id:string;projectId:string;title:string;owner:string;area:string;progress:number;status:"En tiempo"|"En riesgo"|"Fuera de tiempo"|"Completada"};
type Filter="Todos"|"En tiempo"|"En riesgo"|"Crítico";

const U:User[]=[
 {id:"u1",name:"Jorge Mejía",email:"jorge@demo.com",password:"1234",role:"Administrador",area:"Inteligencia de Negocios",leader:"Armando Acosta"},
 {id:"u2",name:"Gabriel Sabogal",email:"gabriel@demo.com",password:"1234",role:"Dirección",area:"Dirección General",leader:"—"},
 {id:"u3",name:"Armando Acosta",email:"armando@demo.com",password:"1234",role:"Líder",area:"Finanzas",leader:"Gabriel Sabogal"},
 {id:"u4",name:"Dante",email:"dante@demo.com",password:"1234",role:"Colaborador",area:"Ventas",leader:"Daniela Juárez"}
];

const P:Project[]=[
 {id:"OBJ-001",name:"Rotación",objective:"Reducir la rotación en un 20% con respecto al año anterior",areas:["Recursos Humanos","Operaciones","Finanzas"],base:42,target:33.6,unit:"% rotación",start:"2025-10-01",end:"2026-09-30",progress:86,owner:"Recursos Humanos",priority:"Alta"},
 {id:"OBJ-002",name:"UBOT",objective:"Reducir 15% el tiempo extra no facturable mediante control preventivo y seguimiento semanal",areas:["Operaciones","Finanzas","Nóminas"],base:100,target:85,unit:"índice TE",start:"2025-10-01",end:"2026-09-30",progress:72,owner:"Operaciones",priority:"Alta"},
 {id:"OBJ-003",name:"Faltas",objective:"Reducir 15% las faltas operativas priorizando servicios críticos y reincidencias",areas:["Operaciones","Recursos Humanos"],base:100,target:85,unit:"índice faltas",start:"2025-10-01",end:"2026-09-30",progress:47,owner:"Operaciones",priority:"Alta"},
 {id:"OBJ-004",name:"Nómina",objective:"Disminuir 30% las incidencias de nómina y cerrar aclaraciones críticas dentro del SLA",areas:["Nóminas","Recursos Humanos","Finanzas"],base:100,target:70,unit:"índice incidencias",start:"2025-10-01",end:"2026-09-30",progress:93,owner:"Nóminas",priority:"Media"},
 {id:"OBJ-005",name:"Comisiones",objective:"Reducir 10% el costo de comisiones sin afectar cobertura ni continuidad operativa",areas:["Finanzas","Operaciones","Ventas"],base:100,target:90,unit:"índice costo",start:"2025-10-01",end:"2026-09-30",progress:61,owner:"Finanzas",priority:"Media"},
 {id:"OBJ-006",name:"Procesos",objective:"Reingeniería y estandarización del 100% de los procesos críticos priorizados",areas:["Inteligencia de Negocios","Tecnología","Finanzas","Recursos Humanos"],base:0,target:12,unit:"procesos",start:"2025-10-01",end:"2026-03-31",progress:78,owner:"Inteligencia de Negocios",priority:"Alta"},
 {id:"OBJ-007",name:"Ventas",objective:"Cumplimiento mensual de cierre de ventas nuevas por línea de negocio",areas:["Ventas","Marketing","Operaciones"],base:681,target:768,unit:"HC",start:"2025-10-01",end:"2026-09-30",progress:34,owner:"Ventas",priority:"Alta"},
 {id:"OBJ-008",name:"Pipeline",objective:"Mantener un pipeline calificado equivalente a 10 veces el presupuesto comercial",areas:["Ventas","Marketing"],base:4.2,target:10,unit:"x presupuesto",start:"2025-10-01",end:"2026-03-31",progress:58,owner:"Ventas",priority:"Alta"},
 {id:"OBJ-009",name:"Cobertura",objective:"Mantener cobertura superior al 98% en servicios prioritarios y disminuir posiciones descubiertas",areas:["Operaciones","Recursos Humanos"],base:94.8,target:98,unit:"% cobertura",start:"2025-10-01",end:"2026-09-30",progress:89,owner:"Operaciones",priority:"Alta"},
 {id:"OBJ-010",name:"Rentabilidad",objective:"Elevar el margen de clientes estratégicos mediante visibilidad de costos y planes correctivos",areas:["Finanzas","Operaciones","Inteligencia de Negocios","Ventas"],base:18,target:22,unit:"% margen",start:"2025-10-01",end:"2026-09-30",progress:53,owner:"Finanzas",priority:"Alta"}
];

const T:Task[]=[
 {id:"t1",projectId:"OBJ-001",title:"Retención servicios críticos",owner:"RH Operativo",area:"Recursos Humanos",progress:88,status:"En tiempo"},
 {id:"t2",projectId:"OBJ-001",title:"Control causas de baja",owner:"Operaciones",area:"Operaciones",progress:79,status:"En tiempo"},
 {id:"t3",projectId:"OBJ-001",title:"Impacto económico",owner:"Controloría",area:"Finanzas",progress:76,status:"En riesgo"},
 {id:"t4",projectId:"OBJ-002",title:"Reglas preventivas TE",owner:"Operaciones",area:"Operaciones",progress:82,status:"En tiempo"},
 {id:"t5",projectId:"OBJ-002",title:"Conciliación TE",owner:"Nóminas",area:"Nóminas",progress:61,status:"En riesgo"},
 {id:"t6",projectId:"OBJ-002",title:"Impacto financiero",owner:"Controloría",area:"Finanzas",progress:45,status:"Fuera de tiempo"},
 {id:"t7",projectId:"OBJ-003",title:"Reincidencias",owner:"RH",area:"Recursos Humanos",progress:70,status:"En riesgo"},
 {id:"t8",projectId:"OBJ-003",title:"Cobertura preventiva",owner:"Operaciones",area:"Operaciones",progress:35,status:"Fuera de tiempo"},
 {id:"t9",projectId:"OBJ-004",title:"Catálogo incidencias",owner:"Nóminas",area:"Nóminas",progress:100,status:"Completada"},
 {id:"t10",projectId:"OBJ-004",title:"SLA aclaraciones",owner:"RH",area:"Recursos Humanos",progress:86,status:"En tiempo"},
 {id:"t11",projectId:"OBJ-004",title:"Control financiero",owner:"Finanzas",area:"Finanzas",progress:92,status:"En tiempo"},
 {id:"t12",projectId:"OBJ-005",title:"Segmentación comisiones",owner:"Finanzas",area:"Finanzas",progress:77,status:"En tiempo"},
 {id:"t13",projectId:"OBJ-005",title:"Plan correctivo",owner:"Operaciones",area:"Operaciones",progress:55,status:"En riesgo"},
 {id:"t14",projectId:"OBJ-005",title:"Criterios comerciales",owner:"Ventas",area:"Ventas",progress:42,status:"Fuera de tiempo"},
 {id:"t15",projectId:"OBJ-006",title:"Inventario de procesos",owner:"BI",area:"Inteligencia de Negocios",progress:100,status:"Completada"},
 {id:"t16",projectId:"OBJ-006",title:"Automatización prioritaria",owner:"Tecnología",area:"Tecnología",progress:64,status:"En riesgo"},
 {id:"t17",projectId:"OBJ-006",title:"Rediseño flujo RH",owner:"RH",area:"Recursos Humanos",progress:78,status:"En tiempo"},
 {id:"t18",projectId:"OBJ-007",title:"Prospección",owner:"Ventas",area:"Ventas",progress:52,status:"En riesgo"},
 {id:"t19",projectId:"OBJ-007",title:"Campañas B2B",owner:"Marketing",area:"Marketing",progress:38,status:"Fuera de tiempo"},
 {id:"t20",projectId:"OBJ-007",title:"Propuestas ágiles",owner:"Operaciones",area:"Operaciones",progress:21,status:"Fuera de tiempo"},
 {id:"t21",projectId:"OBJ-008",title:"ICP",owner:"Ventas",area:"Ventas",progress:72,status:"En riesgo"},
 {id:"t22",projectId:"OBJ-008",title:"Enriquecimiento",owner:"Marketing",area:"Marketing",progress:61,status:"En riesgo"},
 {id:"t23",projectId:"OBJ-009",title:"Semáforo cobertura",owner:"Operaciones",area:"Operaciones",progress:95,status:"En tiempo"},
 {id:"t24",projectId:"OBJ-009",title:"Bolsa candidatos",owner:"RH",area:"Recursos Humanos",progress:83,status:"En tiempo"},
 {id:"t25",projectId:"OBJ-010",title:"Modelo margen",owner:"BI",area:"Inteligencia de Negocios",progress:88,status:"En tiempo"},
 {id:"t26",projectId:"OBJ-010",title:"Costos",owner:"Finanzas",area:"Finanzas",progress:71,status:"En riesgo"},
 {id:"t27",projectId:"OBJ-010",title:"Planes correctivos",owner:"Operaciones",area:"Operaciones",progress:39,status:"Fuera de tiempo"},
 {id:"t28",projectId:"OBJ-010",title:"Renegociación",owner:"Ventas",area:"Ventas",progress:24,status:"Fuera de tiempo"}
];

const expected:Record<string,number>={"OBJ-001":82,"OBJ-002":78,"OBJ-003":65,"OBJ-004":85,"OBJ-005":70,"OBJ-006":75,"OBJ-007":60,"OBJ-008":65,"OBJ-009":85,"OBJ-010":62};
const nav:Record<Role,string[]>={Administrador:["Resumen","Usuarios","Configuración"],Dirección:["Dashboard","Objetivos estratégicos","Organigrama","Alertas"],Líder:["Mis objetivos","Mi equipo","Seguimiento"],Colaborador:["Mis objetivos","Mi plan","Evidencias"]};
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const status=(p:Project):Exclude<Filter,"Todos">=>{const d=p.progress-(expected[p.id]??Math.max(0,p.progress));return d>=-5?"En tiempo":d>=-15?"En riesgo":"Crítico"};
const tone=(s:string)=>s==="En tiempo"?"ok":s==="En riesgo"?"warn":"bad";
const fmt=(n:number)=>Number.isInteger(n)?String(n):n.toFixed(1);

function trendFor(p:Project){const e=expected[p.id]??p.progress;const seed=Number(p.id.replace("OBJ-","")||1);return Array.from({length:11},(_,i)=>{const target=Math.max(4,p.progress-(10-i)*(1.8+(seed%3)*.45));const wave=Math.sin((i+seed)*1.15)*4;return Math.max(0,Math.min(100,Math.round(target+wave)))})}

export default function App(){
 const [user,setUser]=useState<User|null>(null),[page,setPage]=useState(""),[projects,setProjects]=useState<Project[]>(clone(P)),[tasks,setTasks]=useState<Task[]>(clone(T)),[selected,setSelected]=useState("OBJ-001"),[filter,setFilter]=useState<Filter>("Todos"),[detail,setDetail]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{const s=localStorage.getItem("oc-session"),p=localStorage.getItem("oc-projects"),t=localStorage.getItem("oc-tasks");if(s){const x=U.find(u=>u.id===s);if(x){setUser(x);setPage(nav[x.role][0])}}if(p)try{const parsed=JSON.parse(p);if(Array.isArray(parsed)&&parsed.length)setProjects(parsed)}catch{}if(t)try{const parsed=JSON.parse(t);if(Array.isArray(parsed)&&parsed.length)setTasks(parsed)}catch{}},[]);
 useEffect(()=>{localStorage.setItem("oc-projects",JSON.stringify(projects));localStorage.setItem("oc-tasks",JSON.stringify(tasks))},[projects,tasks]);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};
 const resetDemo=()=>{setProjects(clone(P));setTasks(clone(T));setSelected("OBJ-001");setFilter("Todos");setDetail(false);localStorage.setItem("oc-projects",JSON.stringify(P));localStorage.setItem("oc-tasks",JSON.stringify(T));notify("Datos demo restablecidos")};
 if(!user)return <Login enter={u=>{setUser(u);setPage(nav[u.role][0]);localStorage.setItem("oc-session",u.id)}}/>;
 const project=projects.find(p=>p.id===selected)||projects[0];
 const logout=()=>{localStorage.removeItem("oc-session");setUser(null)};
 return <main className="v3"><aside><div className="brand"><b>IC</b><p>INTER-CON<span>OBJETIVOS EN CASCADA</span></p></div><div className="profile"><b>{user.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</b><p>{user.name}<span>{user.role} · {user.area}</span></p></div><nav>{nav[user.role].map((x,i)=><button key={x} className={page===x?"active":""} onClick={()=>{setPage(x);setDetail(false)}}><i>{["▦","◎","♙","⚑"][i]}</i>{x}</button>)}</nav><button className="resetDemo" onClick={resetDemo}>↻ Restablecer datos demo</button><button className="logout" onClick={logout}>Cerrar sesión</button></aside>
 <section className="content"><header className="appHeader"><div><small>FY 2026 · {page.toUpperCase()}</small><h1>{user.role==="Dirección"?"Objetivos Generales 2025–2026":user.role==="Líder"?"Gestión de objetivos":"Portal de objetivos"}</h1><p>{user.role==="Dirección"?"Visión ejecutiva, tendencia y responsables":"Seguimiento de objetivos en cascada"}</p></div>{user.role==="Dirección"&&<div className="headerMark">IC<span>INTER-CON</span></div>}</header>
 {user.role==="Dirección"&&<Director projects={projects} tasks={tasks} project={project} selected={selected} setSelected={setSelected} page={page} filter={filter} setFilter={setFilter} detail={detail} setDetail={setDetail}/>} 
 {user.role==="Administrador"&&<Admin projects={projects}/>} 
 {user.role==="Líder"&&<Leader projects={projects} tasks={tasks}/>} 
 {user.role==="Colaborador"&&<Worker projects={projects} tasks={tasks}/>} 
 </section>{toast&&<div className="toast">✓ {toast}</div>}</main>
}

function Director({projects,tasks,project,selected,setSelected,page,filter,setFilter,detail,setDetail}:{projects:Project[];tasks:Task[];project:Project;selected:string;setSelected:(v:string)=>void;page:string;filter:Filter;setFilter:(v:Filter)=>void;detail:boolean;setDetail:(v:boolean)=>void}){
 if(page==="Organigrama")return <OrgView projects={projects}/>;
 if(page==="Alertas")return <Alerts projects={projects} onOpen={id=>{setSelected(id);setDetail(true)}}/>;
 if(page==="Objetivos estratégicos")return <Objectives projects={projects} selected={selected} setSelected={setSelected} onOpen={()=>setDetail(true)}/>;
 if(detail)return <ObjectiveDetail project={project} tasks={tasks} back={()=>setDetail(false)}/>;
 const counts={Todos:projects.length,"En tiempo":projects.filter(p=>status(p)==="En tiempo").length,"En riesgo":projects.filter(p=>status(p)==="En riesgo").length,"Crítico":projects.filter(p=>status(p)==="Crítico").length};
 const shown=filter==="Todos"?projects:projects.filter(p=>status(p)===filter);
 return <div className="execPage"><div className="execFilters"><label>Año fiscal<select><option>FY2026</option></select></label><label>Periodo<select><option>Agosto 2026</option></select></label><label>Región<select><option>Todas</option></select></label><label>Área<select><option>Todas</option></select></label></div><div className="healthFilters">{(["Todos","En tiempo","En riesgo","Crítico"] as Filter[]).map(x=><button key={x} className={`${filter===x?"active":""} ${x!=="Todos"?tone(x):""}`} onClick={()=>setFilter(x)}><span>{counts[x]}</span>{x}</button>)}</div><div className="execIntro"><div><span>PORTAFOLIO ESTRATÉGICO</span><h2>Resumen ejecutivo de objetivos</h2><p>Meta, resultado actual, avance esperado y desviación en una sola vista.</p></div><strong>{Math.round(projects.reduce((a,p)=>a+p.progress,0)/Math.max(projects.length,1))}%<small>avance global</small></strong></div><div className="objectiveRows">{shown.map(p=><ObjectiveRow key={p.id} p={p} onOpen={()=>{setSelected(p.id);setDetail(true)}}/>)}</div></div>
}

function ObjectiveRow({p,onOpen}:{p:Project;onOpen:()=>void}){const s=status(p),e=expected[p.id]??p.progress,d=p.progress-e;return <article className={`execObjective ${tone(s)}`}><div className="objectiveIdentity"><span>{p.name}</span><h3>{p.objective}</h3><small>{p.owner} · {p.areas.length} áreas involucradas</small></div><div className="metricCard"><small>{p.base===0?"Línea base":"Referencia / base"}</small><b>{fmt(p.base)} <em>{p.unit}</em></b><span>Meta {fmt(p.target)} {p.unit}</span></div><div className="metricCard current"><small>Avance actual</small><b>{p.progress}%</b><span>Esperado a la fecha {e}%</span></div><div className={`resultCard ${tone(s)}`}><small>Estado del objetivo</small><b>{s}</b><span>{d>=0?"+":""}{d} pts vs avance esperado</span><div><i style={{width:`${Math.min(100,p.progress)}%`}}/></div></div><button className="detailBtn" onClick={onOpen}>Ver detalle ↗</button></article>}

function ObjectiveDetail({project,tasks,back}:{project:Project;tasks:Task[];back:()=>void}){const s=status(project),e=expected[project.id]??project.progress,d=project.progress-e,trend=trendFor(project);const pt=tasks.filter(t=>t.projectId===project.id);const areas=project.areas.map(a=>{const xs=pt.filter(t=>t.area===a);return {name:a,progress:xs.length?Math.round(xs.reduce((m,x)=>m+x.progress,0)/xs.length):Math.max(0,project.progress-8)}});return <div className="detailPage"><button className="backBtn" onClick={back}>← Volver al resumen</button><section className="detailHero"><div className="detailLetter">{project.name.charAt(0)}</div><div><span>{project.name}</span><h2>Objetivo · {project.objective}</h2><p>Responsable principal: {project.owner}</p></div><div className={`statusPill ${tone(s)}`}>{s}</div></section><div className="detailKpis"><MiniK label="Línea base" value={`${fmt(project.base)} ${project.unit}`}/><MiniK label="Meta" value={`${fmt(project.target)} ${project.unit}`}/><MiniK label="Avance actual" value={`${project.progress}%`}/><MiniK label="Avance esperado" value={`${e}%`}/><MiniK label="Desviación" value={`${d>0?"+":""}${d} pts`} bad={d<-5}/></div><section className="detailGrid"><article className="chartCard"><div className="sectionTitle">Tendencia mensual · real vs esperado</div><Trend values={trend} expectedValue={e}/></article><article className="areaCard"><div className="sectionTitle">Contribución por área</div>{areas.map(a=><div className="areaLine" key={a.name}><div><b>{a.name}</b><span>{a.progress}%</span></div><div><i style={{width:`${Math.min(100,a.progress)}%`}}/></div></div>)}</article></section><section className="contextCard"><div><small>Qué debe interpretar Dirección</small><b>{d<-15?"El objetivo presenta una desviación material y requiere intervención.":d<-5?"El objetivo requiere seguimiento cercano para recuperar trayectoria.":"El objetivo se mantiene dentro de la trayectoria esperada."}</b></div><div><small>Periodo</small><b>{project.start} → {project.end}</b></div><div><small>Prioridad</small><b>{project.priority}</b></div></section></div>}

function Trend({values,expectedValue}:{values:number[];expectedValue:number}){const months=["Oct","Nov","Dic","Ene","Feb","Mar","Abr","May","Jun","Jul","Ago"];const w=650,h=250,pad=30,max=100;const points=values.map((v,i)=>`${pad+i*((w-pad*2)/(values.length-1))},${h-pad-(v/max)*(h-pad*2)}`).join(" ");const expY=h-pad-(expectedValue/max)*(h-pad*2);return <div className="trendWrap"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Tendencia mensual"><line x1={pad} y1={expY} x2={w-pad} y2={expY} className="expectedLine"/><polyline points={points} className="actualLine"/>{values.map((v,i)=>{const x=pad+i*((w-pad*2)/(values.length-1)),y=h-pad-(v/max)*(h-pad*2);return <g key={i}><circle cx={x} cy={y} r="4"/><text x={x} y={h-7} textAnchor="middle">{months[i]}</text>{(i===0||i===values.length-1)&&<text x={x} y={y-9} textAnchor="middle" className="valueLabel">{v}%</text>}</g>})}</svg><div className="trendLegend"><span><i className="realDot"/>Avance real</span><span><i className="expectedDot"/>Esperado {expectedValue}%</span></div></div>}

function Objectives({projects,selected,setSelected,onOpen}:{projects:Project[];selected:string;setSelected:(v:string)=>void;onOpen:()=>void}){return <div className="simplePage"><section className="pageHero"><span>OBJETIVOS ESTRATÉGICOS</span><h2>Construcción y seguimiento SMART</h2><p>Dirección define el objetivo; los líderes despliegan subobjetivos en cascada.</p></section><div className="objectiveCards">{projects.map(p=><button key={p.id} className={`objectiveCard ${selected===p.id?"selected":""}`} onClick={()=>setSelected(p.id)}><div><span>{p.id}</span><em className={tone(status(p))}>{status(p)}</em></div><h3>{p.name}</h3><p>{p.objective}</p><footer><b>{p.progress}%</b><span>Esperado {expected[p.id]??0}%</span></footer></button>)}</div><button className="openSelected" onClick={onOpen}>Ver detalle del objetivo seleccionado →</button></div>}

function OrgView({projects}:{projects:Project[]}){const people=[{name:"Gabriel Sabogal",role:"Dirección",children:["Armando Acosta","Jacqueline Cortés","Operaciones"]},{name:"Armando Acosta",role:"Finanzas",children:["Controloría","Contabilidad","Nóminas","Pricing","BI"]},{name:"Operaciones",role:"Dirección Operativa",children:["Regiones","Supervisión","Coordinaciones"]}];return <div className="simplePage"><section className="pageHero"><span>ORGANIZACIÓN</span><h2>Objetivos por estructura</h2><p>Consulta la cascada por persona o área sin mezclar actividades con el nivel ejecutivo.</p></section><div className="orgGrid">{people.map((p,i)=><article className="orgPerson" key={p.name}><div className="avatarBig">{p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><h3>{p.name}</h3><span>{p.role}</span><b>{i===0?projects.length:projects.filter(x=>i===1?x.areas.includes("Finanzas"):x.areas.includes("Operaciones")).length} objetivos vinculados</b><div>{p.children.map(c=><em key={c}>{c}</em>)}</div></article>)}</div></div>}

function Alerts({projects,onOpen}:{projects:Project[];onOpen:(id:string)=>void}){const xs=projects.filter(p=>status(p)!=="En tiempo").sort((a,b)=>(a.progress-(expected[a.id]??0))-(b.progress-(expected[b.id]??0)));return <div className="simplePage"><section className="pageHero danger"><span>ALERTAS</span><h2>Objetivos fuera de trayectoria</h2><p>Priorizados por desviación contra el avance esperado a la fecha.</p></section><div className="alertList">{xs.map(p=>{const d=p.progress-(expected[p.id]??p.progress);return <button key={p.id} onClick={()=>onOpen(p.id)}><span className={`alertDot ${tone(status(p))}`}/><div><b>{p.name}</b><small>{p.objective}</small></div><strong>{d} pts</strong><em>{status(p)}</em><i>→</i></button>})}</div></div>}

function Leader({projects,tasks}:{projects:Project[];tasks:Task[]}){const mine=projects.filter(p=>p.areas.includes("Finanzas"));return <div className="simplePage"><section className="pageHero"><span>FINANZAS</span><h2>Mis objetivos y despliegue</h2><p>El líder recibe objetivos corporativos y crea objetivos derivados para su estructura.</p></section><div className="leaderKpis"><MiniK label="Objetivos vinculados" value={String(mine.length)}/><MiniK label="En tiempo" value={String(mine.filter(p=>status(p)==="En tiempo").length)}/><MiniK label="En riesgo" value={String(mine.filter(p=>status(p)!=="En tiempo").length)}/><MiniK label="Avance promedio" value={`${Math.round(mine.reduce((a,p)=>a+p.progress,0)/Math.max(mine.length,1))}%`}/></div><div className="objectiveCards">{mine.map(p=><button className="objectiveCard" key={p.id}><div><span>{p.id}</span><em className={tone(status(p))}>{status(p)}</em></div><h3>{p.name}</h3><p>{p.objective}</p><footer><b>{p.progress}%</b><span>{tasks.filter(t=>t.projectId===p.id&&t.area==="Finanzas").length} contribuciones del área</span></footer></button>)}</div></div>}

function Worker({projects,tasks}:{projects:Project[];tasks:Task[]}){const p=projects.find(x=>x.id==="OBJ-007")||projects[0];const mine=tasks.filter(t=>t.projectId===p.id&&t.area==="Ventas");return <div className="simplePage"><section className="pageHero"><span>MI CONTRIBUCIÓN</span><h2>{p.objective}</h2><p>Las actividades viven en el plan individual, no en el dashboard de Dirección.</p></section><div className="detailKpis"><MiniK label="Avance del objetivo" value={`${p.progress}%`}/><MiniK label="Mi área" value="Ventas"/><MiniK label="Actividades del plan" value={String(mine.length)}/></div><section className="planCard">{mine.map(t=><div key={t.id}><span className={tone(t.status==="Fuera de tiempo"?"Crítico":t.status)}>{t.progress}%</span><p><b>{t.title}</b><small>{t.owner}</small></p><div><i style={{width:`${t.progress}%`}}/></div></div>)}</section></div>}

function Admin({projects}:{projects:Project[]}){return <div className="simplePage"><section className="pageHero"><span>ADMINISTRACIÓN</span><h2>Configuración de Objetivos-IC</h2><p>Demo preparada con estructura portable hacia Airtable/API.</p></section><div className="leaderKpis"><MiniK label="Objetivos demo" value={String(projects.length)}/><MiniK label="Áreas" value={String(new Set(projects.flatMap(p=>p.areas)).size)}/><MiniK label="Usuarios demo" value={String(U.length)}/><MiniK label="FY" value="2026"/></div></div>}

function MiniK({label,value,bad}:{label:string;value:string;bad?:boolean}){return <article className={`miniK ${bad?"bad":""}`}><small>{label}</small><b>{value}</b></article>}

function Login({enter}:{enter:(u:User)=>void}){const [email,setEmail]=useState("gabriel@demo.com"),[password,setPassword]=useState("1234"),[err,setErr]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();const u=U.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(u)enter(u);else setErr("Credenciales incorrectas")};return <main className="loginPage"><section className="loginBrand"><div className="loginLogo">IC</div><span>INTER-CON · FY2026</span><h1>Objetivos estratégicos en cascada</h1><p>Del objetivo corporativo a la contribución individual, con una experiencia alineada al tablero ejecutivo actual.</p><div className="loginFlow"><b>Dirección</b><i>→</i><b>Líderes</b><i>→</i><b>Equipos</b><i>→</i><b>Ejecución</b></div></section><section className="loginPanel"><form onSubmit={submit}><span className="eyebrow">DEMO EJECUTIVA</span><h2>Acceso al portal</h2><p>Selecciona un perfil para recorrer la experiencia.</p>{err&&<div className="loginError">{err}</div>}<label>Correo<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary loginButton">Ingresar</button><div className="demoUsers"><b>Perfiles demo</b>{U.map(u=><button type="button" key={u.id} onClick={()=>{setEmail(u.email);setPassword(u.password)}}><span>{u.role}</span>{u.name}</button>)}<small>Contraseña para todos: 1234</small></div></form></section></main>}
