import {FormEvent,useEffect,useMemo,useState} from "react";

type Role="Administrador"|"Dirección"|"Líder"|"Colaborador";
type User={id:string;name:string;email:string;password:string;role:Role;area:string;leader:string};
type Project={id:string;name:string;objective:string;areas:string[];base:number;target:number;unit:string;start:string;end:string;progress:number;owner:string;priority:"Alta"|"Media"|"Baja"};
type Task={id:string;projectId:string;parentId?:string;title:string;owner:string;area:string;start:string;end:string;progress:number;status:"En tiempo"|"En riesgo"|"Fuera de tiempo"|"Completada"};
type Request={id:string;from:string;fromArea:string;to:string;toArea:string;task:string;status:"Pendiente"|"Aceptada"|"Rechazada";comments:string};

const U:User[]=[
 {id:"u1",name:"Jorge Mejía",email:"jorge@demo.com",password:"1234",role:"Administrador",area:"Inteligencia de Negocios",leader:"Armando Acosta"},
 {id:"u2",name:"Gabriel Sabogal",email:"gabriel@demo.com",password:"1234",role:"Dirección",area:"Dirección General",leader:"—"},
 {id:"u3",name:"Armando Acosta",email:"armando@demo.com",password:"1234",role:"Líder",area:"Finanzas",leader:"Gabriel Sabogal"},
 {id:"u4",name:"Dante",email:"dante@demo.com",password:"1234",role:"Colaborador",area:"Ventas",leader:"Daniela Juárez"}
];

const P:Project[]=[
 {id:"OBJ-001",name:"Rotación sostenible FY26",objective:"Reducir 20% la rotación en los 20 servicios con mayor impacto antes del cierre FY26",areas:["Recursos Humanos","Operaciones","Finanzas"],base:42,target:33.6,unit:"% rotación",start:"2025-10-01",end:"2026-09-30",progress:86,owner:"Recursos Humanos",priority:"Alta"},
 {id:"OBJ-002",name:"Control de tiempo extra",objective:"Reducir 15% el tiempo extra no facturable mediante control preventivo y seguimiento semanal",areas:["Operaciones","Finanzas","Nóminas"],base:100,target:85,unit:"índice TE",start:"2025-10-01",end:"2026-09-30",progress:72,owner:"Operaciones",priority:"Alta"},
 {id:"OBJ-003",name:"Disminución de faltas",objective:"Reducir 15% las faltas operativas priorizando servicios críticos y reincidencias",areas:["Operaciones","Recursos Humanos"],base:100,target:85,unit:"índice faltas",start:"2025-10-01",end:"2026-09-30",progress:47,owner:"Operaciones",priority:"Alta"},
 {id:"OBJ-004",name:"Excelencia en nómina",objective:"Disminuir 30% las incidencias de nómina y cerrar aclaraciones críticas dentro del SLA",areas:["Nóminas","Recursos Humanos","Finanzas"],base:100,target:70,unit:"índice incidencias",start:"2025-10-01",end:"2026-09-30",progress:93,owner:"Nóminas",priority:"Media"},
 {id:"OBJ-005",name:"Eficiencia de comisiones",objective:"Reducir 10% el costo de comisiones sin afectar cobertura ni continuidad operativa",areas:["Finanzas","Operaciones","Ventas"],base:100,target:90,unit:"índice costo",start:"2025-10-01",end:"2026-09-30",progress:61,owner:"Finanzas",priority:"Media"},
 {id:"OBJ-006",name:"Procesos críticos digitalizados",objective:"Digitalizar el 100% de los procesos críticos priorizados antes de finalizar Q2",areas:["Inteligencia de Negocios","Tecnología","Finanzas","Recursos Humanos"],base:12,target:12,unit:"procesos",start:"2025-10-01",end:"2026-03-31",progress:78,owner:"Inteligencia de Negocios",priority:"Alta"},
 {id:"OBJ-007",name:"Crecimiento comercial",objective:"Cumplir la meta mensual de nuevas ventas con foco en oportunidades de mayor margen",areas:["Ventas","Marketing","Operaciones"],base:100,target:130,unit:"índice ventas",start:"2025-10-01",end:"2026-09-30",progress:34,owner:"Ventas",priority:"Alta"},
 {id:"OBJ-008",name:"Pipeline comercial 10x",objective:"Mantener un pipeline calificado equivalente a 10 veces el presupuesto comercial",areas:["Ventas","Marketing"],base:4.2,target:10,unit:"x presupuesto",start:"2025-10-01",end:"2026-03-31",progress:58,owner:"Ventas",priority:"Alta"},
 {id:"OBJ-009",name:"Cobertura operativa",objective:"Mantener cobertura superior al 98% en servicios prioritarios y disminuir posiciones descubiertas",areas:["Operaciones","Recursos Humanos"],base:94.8,target:98,unit:"% cobertura",start:"2025-10-01",end:"2026-09-30",progress:89,owner:"Operaciones",priority:"Alta"},
 {id:"OBJ-010",name:"Rentabilidad por cliente",objective:"Elevar el margen de clientes estratégicos mediante visibilidad de costos y planes correctivos",areas:["Finanzas","Operaciones","Inteligencia de Negocios","Ventas"],base:18,target:22,unit:"% margen",start:"2025-10-01",end:"2026-09-30",progress:53,owner:"Finanzas",priority:"Alta"}
];

const T:Task[]=[
 {id:"t001",projectId:"OBJ-001",title:"Identificar TOP 20 servicios por rotación",owner:"Equipo BI",area:"Inteligencia de Negocios",start:"2025-10-01",end:"2025-10-31",progress:100,status:"Completada"},
 {id:"t002",projectId:"OBJ-001",title:"Plan de retención para servicios críticos",owner:"RH Operativo",area:"Recursos Humanos",start:"2025-11-01",end:"2026-09-15",progress:88,status:"En tiempo"},
 {id:"t003",projectId:"OBJ-001",title:"Seguimiento semanal de causas de baja",owner:"Coordinadores regionales",area:"Operaciones",start:"2025-11-01",end:"2026-09-30",progress:79,status:"En tiempo"},
 {id:"t004",projectId:"OBJ-001",title:"Cuantificar impacto económico de rotación",owner:"Controloría",area:"Finanzas",start:"2026-01-01",end:"2026-08-31",progress:76,status:"En riesgo"},
 {id:"t005",projectId:"OBJ-002",title:"Tablero semanal de TE por servicio",owner:"Equipo BI",area:"Inteligencia de Negocios",start:"2025-10-01",end:"2025-12-15",progress:100,status:"Completada"},
 {id:"t006",projectId:"OBJ-002",title:"Reglas de autorización preventiva",owner:"Operaciones",area:"Operaciones",start:"2025-11-01",end:"2026-04-30",progress:82,status:"En tiempo"},
 {id:"t007",projectId:"OBJ-002",title:"Conciliación TE pagado vs facturado",owner:"Nóminas",area:"Nóminas",start:"2026-01-01",end:"2026-09-30",progress:61,status:"En riesgo"},
 {id:"t008",projectId:"OBJ-002",title:"Análisis de impacto financiero",owner:"Controloría",area:"Finanzas",start:"2026-02-01",end:"2026-09-30",progress:45,status:"Fuera de tiempo"},
 {id:"t009",projectId:"OBJ-003",title:"Mapa de reincidencia por empleado y servicio",owner:"RH Operativo",area:"Recursos Humanos",start:"2025-11-01",end:"2026-02-28",progress:70,status:"En riesgo"},
 {id:"t010",projectId:"OBJ-003",title:"Rutina diaria de cobertura preventiva",owner:"Supervisores",area:"Operaciones",start:"2025-10-15",end:"2026-09-30",progress:52,status:"En riesgo"},
 {id:"t011",projectId:"OBJ-003",title:"Intervención TOP servicios con faltas",owner:"Coordinadores",area:"Operaciones",start:"2026-01-01",end:"2026-07-31",progress:29,status:"Fuera de tiempo"},
 {id:"t012",projectId:"OBJ-004",title:"Catálogo único de incidencias",owner:"Nóminas",area:"Nóminas",start:"2025-10-01",end:"2025-11-30",progress:100,status:"Completada"},
 {id:"t013",projectId:"OBJ-004",title:"Validaciones previas al cierre",owner:"Nóminas",area:"Nóminas",start:"2025-12-01",end:"2026-09-30",progress:96,status:"En tiempo"},
 {id:"t014",projectId:"OBJ-004",title:"SLA de aclaraciones con RH",owner:"Compensaciones",area:"Recursos Humanos",start:"2025-12-01",end:"2026-09-30",progress:84,status:"En tiempo"},
 {id:"t015",projectId:"OBJ-005",title:"Segmentar comisiones facturables y no facturables",owner:"Controloría",area:"Finanzas",start:"2025-10-01",end:"2026-01-31",progress:100,status:"Completada"},
 {id:"t016",projectId:"OBJ-005",title:"Plan correctivo por región",owner:"Operaciones",area:"Operaciones",start:"2026-02-01",end:"2026-08-31",progress:55,status:"En riesgo"},
 {id:"t017",projectId:"OBJ-005",title:"Ajustar criterios comerciales de nuevas cuentas",owner:"Ventas",area:"Ventas",start:"2026-03-01",end:"2026-09-30",progress:28,status:"Fuera de tiempo"},
 {id:"t018",projectId:"OBJ-006",title:"Inventario de procesos críticos",owner:"Equipo BI",area:"Inteligencia de Negocios",start:"2025-10-01",end:"2025-11-15",progress:100,status:"Completada"},
 {id:"t019",projectId:"OBJ-006",title:"Automatizar evaluación de desempeño",owner:"Equipo BI",area:"Inteligencia de Negocios",start:"2025-11-01",end:"2026-03-31",progress:92,status:"En tiempo"},
 {id:"t020",projectId:"OBJ-006",title:"Automatizar presupuesto anual",owner:"Controloría",area:"Finanzas",start:"2026-01-01",end:"2026-05-31",progress:63,status:"En riesgo"},
 {id:"t021",projectId:"OBJ-006",title:"Integración con identidad corporativa",owner:"Tecnología",area:"Tecnología",start:"2026-02-01",end:"2026-04-30",progress:57,status:"En riesgo"},
 {id:"t022",projectId:"OBJ-006",title:"Digitalizar flujo de altas y cambios",owner:"Recursos Humanos",area:"Recursos Humanos",start:"2026-01-15",end:"2026-06-30",progress:78,status:"En tiempo"},
 {id:"t023",projectId:"OBJ-007",title:"Prospección diaria de cuentas objetivo",owner:"Dante",area:"Ventas",start:"2025-10-01",end:"2026-09-30",progress:62,status:"En riesgo"},
 {id:"t024",projectId:"OBJ-007",title:"Campañas B2B segmentadas",owner:"Marketing",area:"Marketing",start:"2025-11-01",end:"2026-09-30",progress:38,status:"Fuera de tiempo"},
 {id:"t025",projectId:"OBJ-007",title:"Reducir tiempo de propuesta comercial",owner:"Operaciones comerciales",area:"Operaciones",start:"2026-01-01",end:"2026-06-30",progress:21,status:"Fuera de tiempo"},
 {id:"t026",projectId:"OBJ-008",title:"Definir ICP y segmentos prioritarios",owner:"Ventas",area:"Ventas",start:"2025-10-01",end:"2025-12-31",progress:100,status:"Completada"},
 {id:"t027",projectId:"OBJ-008",title:"Enriquecimiento continuo de prospectos",owner:"Marketing",area:"Marketing",start:"2026-01-01",end:"2026-09-30",progress:66,status:"En riesgo"},
 {id:"t028",projectId:"OBJ-008",title:"Disciplina semanal de pipeline",owner:"Líderes comerciales",area:"Ventas",start:"2025-11-01",end:"2026-09-30",progress:54,status:"En riesgo"},
 {id:"t029",projectId:"OBJ-009",title:"Semáforo diario de posiciones descubiertas",owner:"Coordinadores regionales",area:"Operaciones",start:"2025-10-01",end:"2026-09-30",progress:95,status:"En tiempo"},
 {id:"t030",projectId:"OBJ-009",title:"Bolsa preventiva de candidatos",owner:"Reclutamiento",area:"Recursos Humanos",start:"2025-10-15",end:"2026-09-30",progress:83,status:"En tiempo"},
 {id:"t031",projectId:"OBJ-010",title:"Modelo de rentabilidad por cliente",owner:"Equipo BI",area:"Inteligencia de Negocios",start:"2025-10-01",end:"2026-02-28",progress:88,status:"En tiempo"},
 {id:"t032",projectId:"OBJ-010",title:"Validar costos directos e indirectos",owner:"Controloría",area:"Finanzas",start:"2025-11-01",end:"2026-04-30",progress:71,status:"En riesgo"},
 {id:"t033",projectId:"OBJ-010",title:"Planes correctivos TOP 10 clientes",owner:"Operaciones",area:"Operaciones",start:"2026-02-01",end:"2026-09-30",progress:39,status:"Fuera de tiempo"},
 {id:"t034",projectId:"OBJ-010",title:"Renegociación de cuentas con margen crítico",owner:"Ventas",area:"Ventas",start:"2026-03-01",end:"2026-09-30",progress:24,status:"Fuera de tiempo"}
];

const R:Request[]=[
 {id:"r1",from:"Daniela Juárez",fromArea:"Ventas",to:"Jorge Mejía",toArea:"Inteligencia de Negocios",task:"Automatizar priorización de prospectos",status:"Pendiente",comments:"Se requiere aumentar volumen sin perder calidad del pipeline."},
 {id:"r2",from:"Operaciones",fromArea:"Operaciones",to:"Recursos Humanos",toArea:"Recursos Humanos",task:"Plan especial de reclutamiento para servicios críticos",status:"Aceptada",comments:"Cobertura por debajo de meta en tres plazas."},
 {id:"r3",from:"Controloría",fromArea:"Finanzas",to:"Operaciones",toArea:"Operaciones",task:"Validar acciones correctivas de rentabilidad",status:"Pendiente",comments:"Revisión conjunta de clientes con margen inferior al objetivo."}
];

const nav:Record<Role,string[]>={Administrador:["Resumen","Portafolio","Usuarios","Aprobaciones"],Dirección:["Dashboard","Objetivos estratégicos","Cascada","Alertas"],Líder:["Mis objetivos","Mi equipo","Asignar actividades","Aprobaciones"],Colaborador:["Mi objetivo","Mis actividades","Mi plan","Solicitudes"]};
const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const health=(p:number)=>p>=75?"En tiempo":p>=50?"En riesgo":"Fuera de tiempo";

export default function App(){
 const [user,setUser]=useState<User|null>(null),[page,setPage]=useState(""),[projects,setProjects]=useState<Project[]>(clone(P)),[tasks,setTasks]=useState<Task[]>(clone(T)),[requests,setRequests]=useState<Request[]>(clone(R)),[selected,setSelected]=useState("OBJ-001"),[toast,setToast]=useState("");
 useEffect(()=>{const s=localStorage.getItem("oc-session"),p=localStorage.getItem("oc-projects"),t=localStorage.getItem("oc-tasks"),r=localStorage.getItem("oc-requests");if(s){const x=U.find(u=>u.id===s);if(x){setUser(x);setPage(nav[x.role][0])}}if(p)try{setProjects(JSON.parse(p))}catch{}if(t)try{setTasks(JSON.parse(t))}catch{}if(r)try{setRequests(JSON.parse(r))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("oc-projects",JSON.stringify(projects));localStorage.setItem("oc-tasks",JSON.stringify(tasks));localStorage.setItem("oc-requests",JSON.stringify(requests))},[projects,tasks,requests]);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2400)};
 const resetDemo=()=>{setProjects(clone(P));setTasks(clone(T));setRequests(clone(R));setSelected("OBJ-001");localStorage.setItem("oc-projects",JSON.stringify(P));localStorage.setItem("oc-tasks",JSON.stringify(T));localStorage.setItem("oc-requests",JSON.stringify(R));notify("Datos demo restablecidos")};
 if(!user)return <Login enter={u=>{setUser(u);setPage(nav[u.role][0]);localStorage.setItem("oc-session",u.id)}}/>;
 const project=projects.find(p=>p.id===selected)||projects[0]; const pt=tasks.filter(t=>t.projectId===project.id);
 const logout=()=>{localStorage.removeItem("oc-session");setUser(null)};
 return <main className="v3"><aside><div className="brand"><b>IC</b><p>INTER-CON<span>OBJETIVOS EN CASCADA</span></p></div><div className="profile"><b>{user.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</b><p>{user.name}<span>{user.role} · {user.area}</span></p></div><nav>{nav[user.role].map((x,i)=><button key={x} className={page===x?"active":""} onClick={()=>setPage(x)}><i>{["▦","◎","☷","⚑"][i]}</i>{x}{x==="Aprobaciones"&&requests.some(r=>r.status==="Pendiente")&&<em>{requests.filter(r=>r.status==="Pendiente").length}</em>}</button>)}</nav><button className="resetDemo" onClick={resetDemo}>↻ Restablecer datos demo</button><button className="logout" onClick={logout}>Cerrar sesión</button></aside>
 <section className="content"><header><div><small>FY 2026 · {page.toUpperCase()}</small><h1>{user.role==="Dirección"?"Dirección estratégica":user.role==="Líder"?"Gestión de mi equipo":user.role==="Colaborador"?"Mi contribución":"Administración del sistema"}</h1><p>{projects.length} objetivos · {new Set(projects.flatMap(p=>p.areas)).size} áreas · {tasks.length} actividades demo</p></div><div><select value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.id} · {p.name}</option>)}</select></div></header>
 {user.role==="Dirección"&&<Director projects={projects} tasks={tasks} project={project} setSelected={setSelected} page={page}/>}
 {user.role==="Administrador"&&<Admin projects={projects} tasks={tasks} requests={requests} setSelected={setSelected}/>}
 {user.role==="Líder"&&<Leader projects={projects} tasks={tasks} requests={requests} project={project}/>}
 {user.role==="Colaborador"&&<Worker project={project} tasks={tasks} update={(id,p)=>setTasks(tasks.map(t=>t.id===id?{...t,progress:p,status:p>=100?"Completada":health(p) as Task["status"]}:t))}/>} 
 </section>{toast&&<div className="toast">✓ {toast}</div>}</main>
}

function Director({projects,tasks,project,setSelected,page}:{projects:Project[];tasks:Task[];project:Project;setSelected:(id:string)=>void;page:string}){
 const areas=useMemo(()=>{const names=[...new Set(projects.flatMap(p=>p.areas))];return names.map(a=>{const xs=tasks.filter(t=>t.area===a);return {a,count:xs.length,progress:xs.length?Math.round(xs.reduce((s,x)=>s+x.progress,0)/xs.length):0}}).sort((a,b)=>b.count-a.count)},[projects,tasks]);
 const avg=Math.round(projects.reduce((s,p)=>s+p.progress,0)/projects.length),good=projects.filter(p=>p.progress>=75).length,risk=projects.filter(p=>p.progress>=50&&p.progress<75).length,bad=projects.filter(p=>p.progress<50).length;
 if(page==="Objetivos estratégicos") return <Portfolio projects={projects} tasks={tasks} setSelected={setSelected}/>;
 if(page==="Alertas") return <><ExecutiveKpis projects={projects} tasks={tasks}/><section className="card"><Title a="Alertas ejecutivas" b="Objetivos y actividades que requieren decisión"/>{projects.filter(p=>p.progress<60).sort((a,b)=>a.progress-b.progress).map(p=><ProjectRow key={p.id} p={p} tasks={tasks} click={()=>setSelected(p.id)}/>)}</section></>;
 if(page==="Cascada") return <><Hero p={project}/><Cascade project={project} tasks={tasks}/></>;
 return <><section className="portfolioHero"><div><span>PORTAFOLIO ESTRATÉGICO · FY2026</span><h2>Visión ejecutiva de objetivos corporativos</h2><p>Seguimiento consolidado de desempeño, dependencias y puntos de atención.</p></div><div className="bigScore"><b>{avg}%</b><span>AVANCE GLOBAL</span></div></section><section className="kpis"><K n={String(projects.length)} l="Objetivos estratégicos" s="Portafolio FY2026"/><K n={String(good)} l="En tiempo" s="Avance ≥ 75%"/><K n={String(risk)} l="En riesgo" s="Avance 50–74%"/><K n={String(bad)} l="Críticos" s="Avance < 50%"/></section><section className="execGrid"><article className="card"><Title a="Salud del portafolio" b="Avance por objetivo"/>{projects.map(p=><div className="objectiveBar" key={p.id} onClick={()=>setSelected(p.id)}><span>{p.id}</span><p><b>{p.name}</b><small>{p.owner}</small></p><div><i className={health(p.progress).replaceAll(" ","-").toLowerCase()} style={{width:p.progress+"%"}}/></div><strong>{p.progress}%</strong></div>)}</article><article className="card"><Title a="Desempeño por área" b="Promedio de actividades"/>{areas.map(x=><div className="areaExec" key={x.a}><p><b>{x.a}</b><span>{x.count} actividades</span></p><div><i style={{width:x.progress+"%"}}/></div><strong>{x.progress}%</strong></div>)}</article></section><section className="card"><Title a="Objetivos que requieren atención" b="Prioridad directiva por menor avance"/>{projects.slice().sort((a,b)=>a.progress-b.progress).slice(0,5).map(p=><ProjectRow key={p.id} p={p} tasks={tasks} click={()=>setSelected(p.id)}/>)}</section><Hero p={project}/><section className="card"><Title a="Detalle del objetivo seleccionado" b={`${tasks.filter(t=>t.projectId===project.id).length} actividades en la cascada`}/>{tasks.filter(t=>t.projectId===project.id).sort((a,b)=>a.progress-b.progress).map(t=><TaskRow t={t} key={t.id}/>)}</section></>;
}

function ExecutiveKpis({projects,tasks}:{projects:Project[];tasks:Task[]}){return <section className="kpis"><K n={String(projects.length)} l="Objetivos" s="FY2026"/><K n={String(tasks.length)} l="Actividades" s="En toda la cascada"/><K n={String(tasks.filter(t=>t.status==="Fuera de tiempo").length)} l="Fuera de tiempo" s="Requieren intervención"/><K n={String(new Set(projects.flatMap(p=>p.areas)).size)} l="Áreas involucradas" s="Trabajo transversal"/></section>}
function Portfolio({projects,tasks,setSelected}:{projects:Project[];tasks:Task[];setSelected:(id:string)=>void}){return <><ExecutiveKpis projects={projects} tasks={tasks}/><section className="portfolioCards">{projects.map(p=>{const xs=tasks.filter(t=>t.projectId===p.id);return <article className="portfolioCard" key={p.id} onClick={()=>setSelected(p.id)}><div><span>{p.id}</span><em className={health(p.progress).replaceAll(" ","-").toLowerCase()}>{health(p.progress)}</em></div><h3>{p.name}</h3><p>{p.objective}</p><small>Responsable · {p.owner}</small><div className="miniProgress"><i style={{width:p.progress+"%"}}/></div><footer><b>{p.progress}% avance</b><span>{xs.length} actividades · {p.areas.length} áreas</span></footer></article>})}</section></>}
function ProjectRow({p,tasks,click}:{p:Project;tasks:Task[];click:()=>void}){const xs=tasks.filter(t=>t.projectId===p.id);return <button className="projectRow" onClick={click}><span className="projectCode">{p.id}</span><p><b>{p.name}</b><small>{p.owner} · {xs.length} actividades</small></p><em className={health(p.progress).replaceAll(" ","-").toLowerCase()}>{health(p.progress)}</em><strong>{p.progress}%</strong><i>→</i></button>}
function Cascade({project,tasks}:{project:Project;tasks:Task[]}){const xs=tasks.filter(t=>t.projectId===project.id);return <section className="card"><Title a="Cascada del objetivo" b="Dirección → área responsable → responsables de ejecución"/><div className="cascadeDemo"><div className="cascadeNode main"><small>DIRECCIÓN</small><b>{project.name}</b><span>{project.progress}% de avance</span></div><i>↓</i><div className="cascadeAreas">{project.areas.map(a=><div className="cascadeNode" key={a}><small>ÁREA</small><b>{a}</b><span>{xs.filter(t=>t.area===a).length} actividades</span></div>)}</div><i>↓</i><div className="cascadeTasks">{xs.map(t=><div className="cascadeNode task" key={t.id}><small>{t.owner}</small><b>{t.title}</b><span>{t.progress}% · {t.status}</span></div>)}</div></div></section>}
function Leader({projects,tasks,requests,project}:{projects:Project[];tasks:Task[];requests:Request[];project:Project}){const mine=projects.filter(p=>p.areas.includes("Finanzas"));return <><section className="kpis"><K n={String(mine.length)} l="Objetivos vinculados" s="Área Finanzas"/><K n={String(tasks.filter(t=>t.area==="Finanzas").length)} l="Actividades" s="Asignadas al área"/><K n={String(requests.filter(r=>r.status==="Pendiente").length)} l="Solicitudes" s="Pendientes de decisión"/><K n={Math.round(mine.reduce((s,p)=>s+p.progress,0)/Math.max(mine.length,1))+"%"} l="Avance promedio" s="Objetivos relacionados"/></section><Hero p={project}/><section className="card"><Title a="Actividades bajo seguimiento" b="Vista del líder"/>{tasks.filter(t=>t.area==="Finanzas"||t.projectId===project.id).slice(0,10).map(t=><TaskRow t={t} key={t.id}/>)}</section></>}
function Worker({project,tasks,update}:{project:Project;tasks:Task[];update:(id:string,p:number)=>void}){const mine=tasks.filter(t=>t.owner==="Dante");return <><Hero p={project}/><section className="card"><Title a="Mis actividades" b="El avance puede modificarse durante la demo"/>{mine.map(t=><div className="workerTask" key={t.id}><div><b>{t.title}</b><span>{t.start} — {t.end}</span></div><strong>{t.progress}%</strong><input type="range" value={t.progress} onChange={e=>update(t.id,+e.target.value)}/><em>{t.status}</em></div>)}</section></>}
function Admin({projects,tasks,requests,setSelected}:{projects:Project[];tasks:Task[];requests:Request[];setSelected:(id:string)=>void}){return <><ExecutiveKpis projects={projects} tasks={tasks}/><section className="card"><Title a="Dataset ejecutivo de demostración" b="Los cambios se conservan localmente hasta restablecer la demo"/><div className="adminFlow">10 objetivos <i>→</i> 8 áreas <i>→</i> 34 actividades <i>→</i> avances mixtos <i>→</i> alertas <i>→</i> cascada</div></section><Portfolio projects={projects} tasks={tasks} setSelected={setSelected}/><section className="card"><Title a="Solicitudes interárea" b="Dependencias simuladas"/>{requests.map(r=><div className="requestMini" key={r.id}><b>{r.fromArea} → {r.toArea}</b><span>{r.task}</span><em>{r.status}</em></div>)}</section></>}
function Hero({p}:{p:Project}){return <section className="hero"><div><span>{p.id} · PRIORIDAD {p.priority.toUpperCase()}</span><h2>{p.objective}</h2><p>{p.name} · Base {p.base} · Meta {p.target} {p.unit}</p><div className="chips">{p.areas.map(a=><b key={a}>{a}</b>)}</div></div><div className="ring"><b>{p.progress}%</b><span>AVANCE</span></div></section>}
function TaskRow({t}:{t:Task}){return <div className="taskRow"><b>{t.area.slice(0,2).toUpperCase()}</b><p><strong>{t.title}</strong><span>{t.owner} · {t.end}</span></p><div><i style={{width:t.progress+"%"}}/></div><em className={t.status.replaceAll(" ","-").toLowerCase()}>{t.status}</em><strong>{t.progress}%</strong></div>}
function K({n,l,s}:{n:string;l:string;s:string}){return <article className="kpi"><b>{n}</b><strong>{l}</strong><span>{s}</span></article>}
function Title({a,b}:{a:string;b:string}){return <div className="title"><div><b>{a}</b><span>{b}</span></div></div>}
function Login({enter}:{enter:(u:User)=>void}){const [email,setEmail]=useState("gabriel@demo.com"),[password,setPassword]=useState("1234"),[err,setErr]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();const u=U.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(u)enter(u);else setErr("Credenciales incorrectas")};return <main className="loginPage"><section className="loginBrand"><div className="loginLogo">IC</div><span>INTER-CON · FY2026</span><h1>Objetivos estratégicos en cascada</h1><p>De la estrategia de Dirección a la ejecución diaria, con trazabilidad de responsables, avances, dependencias y alertas.</p><div className="loginFlow"><b>Dirección</b><i>→</i><b>Líderes</b><i>→</i><b>Equipos</b><i>→</i><b>Ejecución</b></div></section><section className="loginPanel"><form onSubmit={submit}><span className="eyebrow">DEMO EJECUTIVA</span><h2>Acceso al portal</h2><p>Selecciona un perfil para recorrer la experiencia completa.</p>{err&&<div className="loginError">{err}</div>}<label>Correo<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary loginButton">Ingresar</button><div className="demoUsers"><b>Perfiles demo</b>{U.map(u=><button type="button" key={u.id} onClick={()=>{setEmail(u.email);setPassword(u.password)}}><span>{u.role}</span>{u.name}</button>)}<small>Contraseña para todos: 1234</small></div></form></section></main>}
