import React from "react";
import ReactDOM from "react-dom/client";
import "./demoMigration";
import App from "./App";
import SmartCreator from "./SmartCreator";
import "./index.css";
import "./local.css";
import "./v3.css";
import "./demo.css";
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App /><SmartCreator /></React.StrictMode>);
