import {FormEvent,useEffect,useState} from "react";

type DemoProject={id:string;name:string;objective:string;areas:string[];base:number;target:number;unit:string;start:string;end:string;progress:number;owner:string;priority:"Alta"|"Media"|"Baja"};
const AREAS=["Operaciones","Finanzas","Recursos Humanos","Ventas","Marketing","Nóminas","Inteligencia de Negocios","Tecnología"];

export default function SmartCreator(){
 const [direction,setDirection]=useState(false),[open,setOpen]=useState(false),[title,setTitle]=useState(""),[specific,setSpecific]=useState(""),[indicator,setIndicator]=useState(""),[base,setBase]=useState(0),[target,setTarget]=useState(0),[unit,setUnit]=useState("%"),[deadline,setDeadline]=useState("2026-09-30"),[areas,setAreas]=useState<string[]>([]),[priority,setPriority]=useState<"Alta"|"Media"|"Baja">("Alta"),[ai,setAi]=useState(false);
 useEffect(()=>{const check=()=>setDirection(localStorage.getItem("oc-session")==="u2");check();const id=setInterval(check,500);return()=>clearInterval(id)},[]);
 if(!direction)return null;
 const score=[specific,indicator,target>0,deadline,areas.length>0].filter(Boolean).length*20;
 const toggle=(a:string)=>setAreas(xs=>xs.includes(a)?xs.filter(x=>x!==a):[...xs,a]);
 const improve=()=>{setAi(true);if(!specific&&title)setSpecific(`Lograr ${title.toLowerCase()} con seguimiento mensual y responsables definidos`);if(!indicator)setIndicator("Indicador clave de resultado")};
 const save=(e:FormEvent)=>{e.preventDefault();if(score<80)return;const current:DemoProject[]=JSON.parse(localStorage.getItem("oc-projects")||"[]");const next=(current.reduce((m,p)=>Math.max(m,Number(p.id?.replace("OBJ-","")||0)),0)+1).toString().padStart(3,"0");const objective=`${specific}. Pasar de ${base} a ${target} ${unit} antes del ${deadline}, medido mediante ${indicator}.`;const p:DemoProject={id:`OBJ-${next}`,name:title||"Nuevo objetivo estratégico",objective,areas,base,target,unit,start:"2025-10-01",end:deadline,progress:0,owner:areas[0]||"Dirección",priority};localStorage.setItem("oc-projects",JSON.stringify([...current,p]));setOpen(false);location.reload()};
 return <><button className="smartFloat" onClick={()=>setOpen(true)}>✦ Crear objetivo SMART</button>{open&&<div className="smartBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form className="smartModal" onSubmit={save}><div className="smartTop"><div><span>✦ ASISTENTE SMART</span><h2>Crear objetivo estratégico</h2><p>El objetivo debe ser específico, medible, alcanzable, relevante y temporal.</p></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><div className="smartScore"><b>{score}/100</b><div><i style={{width:score+"%"}}/></div><span>{score>=80?"Listo para crear":"Completa los criterios SMART"}</span></div><div className="smartBadges"><b>S <span>Específico</span></b><b>M <span>Medible</span></b><b>A <span>Alcanzable</span></b><b>R <span>Relevante</span></b><b>T <span>Temporal</span></b></div><label>Nombre ejecutivo del objetivo<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ej. Reducir rotación operativa" required/></label><label>¿Qué se quiere lograr?<textarea value={specific} onChange={e=>setSpecific(e.target.value)} placeholder="Describe el resultado concreto" required/></label><div className="smartFields"><label>Indicador<input value={indicator} onChange={e=>setIndicator(e.target.value)} placeholder="Ej. % de rotación" required/></label><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value as any)}><option>Alta</option><option>Media</option><option>Baja</option></select></label></div><div className="smartFields three"><label>Base<input type="number" value={base} onChange={e=>setBase(+e.target.value)}/></label><label>Meta<input type="number" value={target} onChange={e=>setTarget(+e.target.value)} required/></label><label>Unidad<input value={unit} onChange={e=>setUnit(e.target.value)}/></label></div><label>Fecha límite<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} required/></label><label>Áreas responsables<div className="smartAreas">{AREAS.map(a=><button type="button" className={areas.includes(a)?"on":""} onClick={()=>toggle(a)} key={a}>{a}</button>)}</div></label>{ai&&<div className="smartAi">✦ La IA estructuró el objetivo para que sea medible y temporal. Puedes ajustar el texto antes de crearlo.</div>}<div className="smartActions"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button type="button" className="smartAiBtn" onClick={improve}>✦ Mejorar con IA</button><button className="primary" disabled={score<80}>Crear objetivo</button></div></form></div>}</>}
